# Site settings
name: yofred moik
title: 5087350340
email: ytmoik@gmail.com
description: "This is where I keep some useful information about what I'm doing with my life."
baseurl: "http://www.yof.red/"
url: "http://www.yof.red/"
timezone: America/New_York

# Build settings
markdown: kramdown
permalinks: pretty