# Site settings
name: yofred moik
title: 5087350340
email: ytmoik@gmail.com
description: "This is where I keep some useful information about what I'm doing with my life."
baseurl: ""
url: "http://yourdomain.com"
timezone: America/New_York

# Build settings
markdown: kramdown
permalinks: pretty